### ISSUE TITLE
Modify Vote Option Names

### ISSUE THREAD

**Issue by themaeso** [Kek5chen/TwitchVotes#2]
Hello! I would like to know if it is possible to modify the ''vote keys'' of TwitchVotes. For example, that people have to write some words in the chat like blue, red. No need to always do it with A, B, C, D...

I guess it's hidden in tmi.min.js but I can't find it.

**Comment by Kek5chen** [comment]
This is possible. I could add a configuration option for it, but this was not the intended way.
For now you can edit this function:
https://github.com/Kek5chen/TwitchVotes/blob/5acfa7c7d07f56038ced889c27ca4168ab2b4853/js/bars.js#L25-L28

Make sure to return a number from 0-5, and -1 if none match, which denotes the options from top to bottom.

You could do:
```js
const options = ["test1", "test2", "test3", "test4", "test5"];
const voteToIndex = msg => options.indexOf(msg?.toLowerCase().split(' ')[0]);
```

**Dont put this code inside of the function. Replace the function with it.**

**Comment by Kek5chen** [comment]
Closed due to inactivity
